//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ichup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public long id { get; set; }
        public Nullable<int> title_id { get; set; }
        public string token { get; set; }
        public string link { get; set; }
        public string link_watermark { get; set; }
        public string link_thumbail { get; set; }
        public Nullable<int> total_views { get; set; }
        public Nullable<int> total_buy { get; set; }
        public Nullable<int> total_download { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<System.DateTime> date_post { get; set; }
    }
}
