//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ichup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public long id { get; set; }
        public string name { get; set; }
        public string des { get; set; }
        public string keyword { get; set; }
        public string link0 { get; set; }
        public string link0w { get; set; }
        public string link1 { get; set; }
        public string link1w { get; set; }
        public string link2 { get; set; }
        public string link2w { get; set; }
        public Nullable<int> total_views0 { get; set; }
        public Nullable<int> total_views1 { get; set; }
        public Nullable<int> total_views2 { get; set; }
        public Nullable<int> total_buy1 { get; set; }
        public string total_buy2 { get; set; }
        public Nullable<int> total_download0 { get; set; }
        public string total_download1 { get; set; }
        public string total_download2 { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<System.DateTime> date_post { get; set; }
        public Nullable<int> cate_id { get; set; }
        public Nullable<byte> free_price { get; set; }
    }
}
