//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ichup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class price_pack
    {
        public int id { get; set; }
        public string pack_name { get; set; }
        public Nullable<decimal> pack_price { get; set; }
        public Nullable<int> months { get; set; }
        public Nullable<int> daily_limited { get; set; }
    }
}
