//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ichup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_log
    {
        public long id { get; set; }
        public Nullable<long> image_id { get; set; }
        public Nullable<int> member_id_buy { get; set; }
        public Nullable<System.DateTime> date_sale { get; set; }
    }
}
